name: Build
on: push

jobs:
  build_image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: cd web
      - run: npm install
      - run: npm run build
      - run: mv dist/* ../server/public
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: huang825172/mirage-test
          dockerfile: tools/build/Dockerfile
          tags: latest