name: Docker Image
on: push

jobs:
  build_image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Run webpack build
        working-directory: ./web
        run: |
          npm install
          npm run build
          mv dist/* ../server/public
      - run: ${{ secrets.MYSQL_URL }} > ./server/mysql_url
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: huang825172/mirage-test
          dockerfile: build/Dockerfile
          tags: latest